# Generated by Django 5.0.4 on 2026-05-25 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='emissions.company')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_index', models.IntegerField(help_text='Row number in original CSV, 1-indexed')),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 – Direct Emissions'), ('scope2', 'Scope 2 – Indirect (Electricity)'), ('scope3', 'Scope 3 – Value Chain')], max_length=10)),
                ('activity_type', models.CharField(help_text='e.g. diesel, electricity, flight', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit', models.CharField(help_text='Normalized unit: L, kWh, km', max_length=20)),
                ('activity_date', models.DateField(help_text='Normalized to YYYY-MM-DD')),
                ('location', models.CharField(blank=True, help_text='Plant code, meter ID, or route', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Free text context from source')),
                ('raw_data', models.JSONField(help_text='Original CSV row, unmodified')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed – Parse Error')], default='pending_review', max_length=20)),
                ('flag', models.CharField(choices=[('ok', 'No Issues'), ('suspicious', 'Suspicious – Needs Attention'), ('failed', 'Failed – Could Not Parse')], default='ok', max_length=12)),
                ('flag_reason', models.TextField(blank=True, help_text='Why this row was flagged')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.datasource')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('edited', 'Edited Before Approval'), ('uploaded', 'Batch Uploaded')], max_length=20)),
                ('detail', models.TextField(blank=True, help_text='What changed, or why rejected')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.datasource')),
                ('record', models.ForeignKey(blank=True, help_text='Null for batch-level events like uploads', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysts', to='emissions.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['company', 'status'], name='emissions_e_company_d710e1_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['company', 'scope'], name='emissions_e_company_92286d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['data_source'], name='emissions_e_data_so_ab2dc3_idx'),
        ),
    ]
